id: ID9B7750F
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T08:40:23+00:00'
last_modified: '2022-06-07T20:42:25.442924+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG25243
  title: དགའ་ལྡན་ལྷ་བརྒྱ་དང་ཐུན་དྲུག་གི་འཁྲིད་སོགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    0B8B:
      image_group_id: I1KG25245
      title: ''
      total_pages: 148
      order: 1
      base_file: 0B8B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
