id: P004161
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG25243
  title: དགའ་ལྡན་ལྷ་བརྒྱ་དང་ཐུན་དྲུག་གི་འཁྲིད་སོགས།
  author: ''
  volumes:
    5043f7f7cd064b87b545015081d46d37:
      image_group_id: I1KG25245
      title: ''
      volume_number: 1
      total_pages: 148
      base_file: v001.txt
